services:
  - type: web
    name: portal-hr-pro-contratacion
    env: python
    plan: free
    buildCommand: pip install -r requirements.txt
    startCommand: gunicorn app:app --workers 1 --threads 2 --timeout 120 --access-logfile - --error-logfile -
    envVars:
      - key: PYTHON_VERSION
        value: 3.11.9
      - key: APP_TIMEZONE
        value: America/Lima
      - key: SECRET_KEY
        generateValue: true
